# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress parallel Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install npm and verify Cypress
      run: |
           npm ci && npx cypress verify
    - name: Execute Cypress e2e tests 
      run: |
        npm run cy:run:parallel
        
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Execution Report
        path: ${{ github.workspace }}/TestReports
        
    - name: Publish Cypress Test Results    
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: TestReports/*.xml
        check_name: Cypress Test Result
        
        
