# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install && Verify Cypress
      run: |
        npm ci && npx cypress verify
    - name: Execute Cypress e2e tests 
      run: |
        npm run cy:run:parallel




